version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test
          command: mvn test
orbs:
  codecov: codecov/codecov@4.0.1
workflows:
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          flags: unit
          name: codecov-umbrella
          token: $CODECOV_TOKEN
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master