version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Run Maven Test
          command: mvn test -X
      - run:
          name: coverage
          command: mvn jacoco:report
      - run:
          name: upload-to-codecov
          command: |
            # Ajoutez ici une étape de débogage pour vérifier le contenu du script bash téléchargé
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
  upload-to-codecov:
    jobs:
      - build-and-test
