version: 2.1

orbs:
  codecov: codecov/codecov@1.0.1

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - build-and-test
      - codecov/upload:
          requires:
            - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test
          command: mvn test
      - codecov/upload:
          token: YOUR_CODECOV_TOKEN
