version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test
          command: mvn clean test -X
      - run:
          name: coverage
          command: mvn jacoco:report
      - run:
          name: upload-to-codecov
          command: bash <(curl -s https://codecov.io/bash)


workflows:
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
  upload-to-codecov:
    jobs:
      - build-and-test