version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test
          command: mvn test
      - codecov/upload:
          token: YOUR_CODECOV_TOKEN

  build-and-test-on-master:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test on Master
          command: mvn test
      - codecov/upload:
          token: YOUR_CODECOV_TOKEN
